Feature: Fill and convert Lead in Salesforce	

Scenario: Fill and convert Lead in Salesforce	

Given I open the test instance of salesforce
When I enter Login and Password
Then I should login to Salesforce
When I click on "Setup"
Then I can see view "Setup_Menu"
When I click on "Manage Users"
Then I am on page "Users"
When I click on "Users"
Then I can see view "Select"
When I select item "6" in menu "fcf"
When I click on "Login"
Then I can see view "Home"
When I switch to tab "Leads"
When I press button "New"
Then I can see view "New_Lead"
When I select "Mr." in menu "name_salutationlea2"
When I fill dynamic field "firstname"
When I fill dynamic field "lastname"
When I fill dynamic field "company"
When I fill dynamic field "gmcnum"
When I fill dynamic field "othernum"
When I fill static field "email"
When I fill static field "phone"
When I populate static field "Date of Birth"
When I select "Male" in menu "00Ng0000001N4rn"
When I select "GMC" in menu "00Ng0000001Mh6e"
When I select "Letter" in menu "lea5"
When I select "Newcastle" in menu "00Nw0000008Lght"
When I select "Surgery" in menu "00Ng0000001NFro"
When I click on button " Save "
Then I can see view "Created_Lead"
When I save values for form "Lead"
When I click on button "Convert"
Then I can see view "Convert"
#When I populate static field "Subject"
When I click on button "Convert"
Then I can see view "Account"
When I click on link "Contact"
Then I can see view "Contact"
